title: 'underTree.io'
author: Shawn Sherwood
description:  >
  // TODO: A blog about the things that I should have already blogged about...
github_username:  ssherwood
twitter_username: shawn_sherwood
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - github-pages
  - minima
exclude:
  - Gemfile
  - Gemfile.lock
