title: '//TODO: A Blog'
author: Shawn Sherwood
description: > # 
  A blog about the things that I should have already blogged about...

url: 'https://ssherwood.github.io'
twitter_username: shawn_sherwood
github_username:  ssherwood

github:
  is_project_page: false
  is_user_page: true

show_downloads: false
google_analytics:

# Build settings
theme: jekyll-theme-minimal
gems:
  - jekyll-feed
  - github-pages
exclude:
  - Gemfile
  - Gemfile.lock
